#!/bin/bash

a="drzewa jtp-lab listy sortowania asd"

for x in $a; do
	cd $x;
	if [ ! -x testerka ]; then
		make testerka > /dev/null 2&> /dev/null;
	fi;
	if [ -x testerka ]; then ./testerka; fi;
	cd ..;
done;
